apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sb-monitor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vensr/sb-monitor-deploy.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: sb-monitor

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true