apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-monitor
spec:
  selector:
    matchLabels:
      app:  sb-monitor
  replicas: 3
  template:
    metadata:
      labels:
        app: sb-monitor
    spec:
      containers:
      - name: sb-monitor
        image: 11061999/sb-monitor:latest
        ports:
        - containerPort: 8080
